[package]
name = "axum_java_executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.2.5"
regex = "1.9.5"
tokio = { version = "1", features = ["full"] }


